name: Detekt and unit tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Detekt Verification
        run: ./gradlew detekt
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test

